title: Set up a security reporting
description: Set up a security reporting process
template:
  repo: security-reporting-template
  name: security-reporting
before:
  - type: updateBranchProtection

  - type: createIssue
    title: Add a Security Policy
    body: 05_add-security-policy.md #security policy issue body (add branch name instructions and examples)
    store:
      policyIssueUrl: '{{ result.data.html_url }}'
      policyIssueNumber: '{{ result.data.number }}'
      # securityIssue


steps:

  # Step 6
  # Learner adds a security polcy through the security tab thereby creating a new PR
  # Bot approves the PR
  # Bot prompts user to merge when ready

  - title: Add a SECURITY.md file
    description: Add a SECURITY.md file to your repository.
    event: 
      - pull_request.opened
      - pull_request.synchronize
    link: '{{ store.policyIssueUrl }}'
    actions:
      - type: getFileContents
        filename: SECURITY.md
        required: false
        action_id: root

      - type: getFileContents
        filename: docs/SECURITY.md
        required: false
        action_id: inDocs

      - type: getFileContents
        filename: .github/SECURITY.md
        required: false
        action_id: inGitHub

      - type: gate
        gates:
        - left: '{{ actions.root }}'
        - left: '{{ actions.inDocs }}'
        - left: '{{ actions.inGitHub }}'
        else: 
        - type: respond
          with: e-debug.md
          data:
            root: '{{ actions.root }}'
            inDocs: '{{ actions.inDocs }}'
            inGitHub: '{{ actions.inGitHub }}'
      - type: createReview
        event: APPROVE
        body: 06_suggest-merge.md #error response that PR was closed not merged. Reopen PR
        store:
          securityPrUrl: '{{ payload.pull_request.html_url }}'
          securityPrTitle: '{{ payload.pull_request.title }}'
      - type: closeIssue
        issue: '{{ store. policyIssueNumber }}'

  # Step 7

  - title: Merge the SECURITY.md pull request
    description: Merge the pull request.
    event: pull_request.closed
    link: "{{ store.securityPrUrl }}"
    actions:
      - type: gate
        every: true
        gates:
        - left: "{{ payload.pull_request.merged }}"
        - left: '{{ payload.pull_request.title }}'
          operator: ===
          right: '{{ store.securityPrTitle }}'
        else:
          - type: respond
            with: 06_accidental-close.md
      - type: respond
        with: 06_good-merge.md


tags: [
  "Security", "Dependency management", "Rebasing", "Auditing", "Dependabot"
]